#!/bin/bash

# Pre-execution cleanup
# Truncate the cron execution log
> /var/log/alibabaIpCron.log

# Initialize the cron execution log
echo -e "#####\n# $(date) - Alibaba IP scan log\n#####\n" | tee /var/log/alibabaIpCron.log

# Remove the alibabaFullIpList file if exists
if [ -f /var/tmp/alibabaFullIpList ]; then
  rm /var/tmp/alibabaFullIpList
  echo "\# Cleaned up existing /var/tmp/alibabaFullIpList file." | tee /var/log/alibabaIpCron.log
fi

# Remove the alibabaIpGroups file if exists
if [ -f /var/tmp/alibabaIpGroups ]; then
  rm /var/tmp/alibabaIpGroups
  echo "\# Cleaned up existing /var/tmp/alibabaIpGroups file." | tee /var/log/alibabaIpCron.log
fi

echo -e "# Scan started.\n" >> /var/log/alibabaIpCron.log
echo -e "# Found log files;\n$(find /home/*/var/*/logs/transfer*.log)\n" | tee /var/log/alibabaIpCron.log

# Generate a temp list of all identified alibaba IPs, assuming they start with "47"
# TO-DO: 
find /home/*/var/*/logs/transfer*.log |
while read line; do
  cat "$line" |
  awk -F' \\[' '{print $1}' |
  sed 's/ /\n/g;s/\-/\n/g' |
  grep '.' |
  awk -F'.' '{if($1=="47"){print $1"."$2"."$3"."$4};}'
done |
sort |
uniq > /var/tmp/alibabaFullIpList

alibabaIpsTotal="$(cat /var/tmp/alibabaFullIpList | wc -l)"
alibabaIpCounter=0
alibabaTime=$(( alibabaIpsTotal / 60 ))

echo -e "Scan complete, found $alibabaIpsTotal IPs in total." | tee /var/log/alibabaIpCron.log
#echo -e "Validating IP addresses (estimated time: $alibabaTime minutes)..." | tee /var/log/alibabaIpCron.log

# This block validates the ownership of the IP. Need to revisit this as whois has a 5k daily request limit at a rate limit of 50 requests per second before getting blocked for 24 hours
#cat /var/tmp/alibabaFullIpList |
#while read line; do
#  ((alibabaIpCounter++))
#  echo -ne "Processing $alibabaIpCounter/$alibabaIpsTotal..."\\r
#  if whois "$line" | grep 'OrgTechName\|OrgAbuseEmail' | grep -qi "alibaba"; then
#    echo "$line" | awk -F'.' '{print $1"."$2"."$3}' >> /var/tmp/alibabaIpGroups
#  fi
#  sleep 1
#done
cat /var/tmp/alibabaFullIpList |
awk -F'.' '{print $1"."$2"."$3}' |
sort |
uniq > /var/tmp/alibabaIpGroups

cat /var/tmp/alibabaIpGroups |
sort

#cat /var/tmp/alibabaFullIpList |
#awk -F'.' '{print $1"."$2"."$3}' |
#sort |
#uniq > /var/tmp/alibabaIpGroups

#cat /var/tmp/alibabaIpGroups |
#while read line; do
#  tmpLowestVal="$(grep "$line" /var/tmp/alibabaFullIpList | awk -F'.' '{print $4}' | sort -n | head -n1)"
#  tmpHighestVal="$(grep "$line" /var/tmp/alibabaFullIpList | awk -F'.' '{print $4}' | sort -n | tail -n1)"
#  echo "$line.$tmpLowestVal $line.$tmpHighestVal"
#done > /var/tmp/alibabaIpRanges
